Depositコンポーネントとstorybookの作成
hirokitanya/next-storybook-for-beginners pull request #1
Opened 2024-07-04 03:43 UTC by hirokitanya

- [ ] app/dashboard/deposit.tsx を作成
- [ ] interface DepositData をpropsとして受け取るようにする
- [ ] app/dashboard/deposit.stories.tsx を作成（chart.stories.tsx を参考に中身を作成）
- [ ] ダッシュボードページを参考にコンポーネントを作成

キャプチャー
![スクリーンショット 2024-07-04 124031](https://github.com/fox-hound-ltd/next-storybook-for-beginners/assets/174312365/5ed2c55f-e045-4887-a75d-9fbe468dd184)
![スクリーンショット 2024-07-04 124105](https://github.com/fox-hound-ltd/next-storybook-for-beginners/assets/174312365/dd0b00c0-3796-46fd-b7b0-6c5a1fa6604b)

2024-07-04 03:54 UTC, fox-shun-nakagawa commented on app/dashboard/chart.tsx
> +  console.log(data);
console.logは削除してください。

2024-07-04 03:54 UTC, fox-shun-nakagawa commented on app/dashboard/deposit.tsx
> +// import './deposit.css';
不要であればコメントアウトは削除してください。

2024-07-04 03:54 UTC, fox-shun-nakagawa commented on app/dashboard/deposit.tsx
> +    <Card sx={{ minWidth: 275, minHeight: 192 }} className="relative mx-5 h-48 p-2">
sxは使用せず、Tailwindで表現してみてください。
同等のスタイルが表現できると思います。

2024-07-04 03:54 UTC, fox-shun-nakagawa commented on app/dashboard/deposit.tsx
> +        <Typography sx={{ mb: 1.5 }} color="text.secondary">
上記と同様です。

2024-07-04 03:54 UTC, fox-shun-nakagawa commented on app/dashboard/deposit.tsx
> +// function getAfterPoint(num:string){
コメントアウトは不要なら削除でお願いします。

2024-07-05 02:16 UTC, fox-Taisei-Nakamura requested changes

2024-07-05 02:16 UTC, fox-Taisei-Nakamura commented on app/dashboard/page.tsx
> +      amount: 3024.0,
固定値を設定していますが、31行目でデータを取得しているのか、取得してデータを表示するようにしてください
storybookの表示ではなく、localhostでの表示の内容になります

2024-07-05 02:16 UTC, fox-Taisei-Nakamura commented on app/dashboard/chart.tsx
> +  console.log(data);
削除されてませんがコミット忘れですか？

2024-07-05 02:47 UTC, hirokitanya commented on app/dashboard/page.tsx
> +      amount: 3024.0,
固定値の設定を外し、mockからのデータを取得するように変更しました

2024-07-05 02:47 UTC, hirokitanya commented on app/dashboard/chart.tsx
> +  console.log(data);
確認漏れでした、該当箇所を削除しました。

2024-07-05 03:00 UTC, hirokitanya commented on app/dashboard/deposit.tsx
> +// import './deposit.css';
不要なため、削除しました

2024-07-05 03:01 UTC, hirokitanya commented on app/dashboard/deposit.tsx
> +    <Card sx={{ minWidth: 275, minHeight: 192 }} className="relative mx-5 h-48 p-2">
sxを削除し、tailwindの内容を修正しました。

2024-07-05 03:01 UTC, hirokitanya commented on app/dashboard/deposit.tsx
> +        <Typography sx={{ mb: 1.5 }} color="text.secondary">
sxを削除し、tailwindの内容を修正しました。

2024-07-05 03:02 UTC, hirokitanya commented on app/dashboard/deposit.tsx
> +// function getAfterPoint(num:string){
コメントアウト部分は必要だったため、コメントアウトを外しました、また内容に修正が必要だったため修正しました。

2024-07-05 03:07 UTC, fox-Taisei-Nakamura approved these changes

2024-07-05 03:08 UTC, merged