Ordersコンポーネントとstorybookの作成
hirokitanya/next-storybook-for-beginners pull request #2
Opened 2024-07-04 10:24 UTC by hirokitanya

- [s] app/dashboard/order.tsx を作成
- [s] interface OrderData をpropsとして受け取るようにする
- [s] app/dashboard/order.stories.tsx を作成（chart.stories.tsx を参考に中身を作成）
- [s] ダッシュボードページを参考にコンポーネントを作成
![スクリーンショット 2024-07-04 192308](https://github.com/hirokitanya/next-storybook-for-beginners/assets/174312365/76ed514c-d3ec-4d95-a9bf-20e67428c8b2)
![スクリーンショット 2024-07-04 192047](https://github.com/hirokitanya/next-storybook-for-beginners/assets/174312365/58287f37-377f-4314-8175-9ad33664f407)

2024-07-04 10:59 UTC, fox-Taisei-Nakamura requested changes

2024-07-04 10:59 UTC, fox-Taisei-Nakamura commented on app/dashboard/order.tsx
> +                <TableCell align="right">${row.amount}</TableCell>
サンプルは、小数点第二まで表示しています

2024-07-04 11:00 UTC, fox-Taisei-Nakamura requested changes

2024-07-04 11:00 UTC, fox-Taisei-Nakamura commented on app/dashboard/order.tsx
> +  return date[2] + ' ' + date[1] + ',' + date[3];
storybookの表示で、カンマが２続いて表示されています。

2024-07-05 02:30 UTC, hirokitanya commented on app/dashboard/order.tsx
> +                <TableCell align="right">${row.amount}</TableCell>
functionを追加し、少数点第二まで表示するように修正しました。

2024-07-05 02:30 UTC, hirokitanya commented on app/dashboard/order.tsx
> +  return date[2] + ' ' + date[1] + ',' + date[3];
order.stories内のdateの内容を変更しました。

2024-07-05 03:31 UTC, fox-Taisei-Nakamura approved these changes

2024-07-05 03:32 UTC, merged