figmaの画面を作成
hirokitanya/next-storybook-for-beginners pull request #6
Opened 2024-07-08 11:11 UTC by hirokitanya

1.ページ上部のSign inの文字とアイコンを業務管理システムと変更する。
2.パスワードのテキストボックスの下に「パスワードを忘れた方は管理者にご連絡ください」と表示する
3.ログインボタンの下のlinkを削除する
4.ページ下部にcopylightの「© 2024 サンプル空調」と追加する
5.メールアドレスのplaceholderを[example@example.com](mailto:example@example.com)に変更する
6.パスワードのplaceholderを**********に変更する
7.テキストボックス内上部の文言を最初から表示するように変更する
8.テキストボックス同士の間隔を狭める
9.画面を437pxと587pxに分割し、左側に写真を表示できるようにする

![スクリーンショット 2024-07-08 201036](https://github.com/hirokitanya/next-storybook-for-beginners/assets/174312365/09d340f8-ac1c-4a02-ba51-77bf55759677)

2024-07-08 11:28 UTC, fox-Taisei-Nakamura requested changes

2024-07-08 11:28 UTC, fox-Taisei-Nakamura commented on app/auth/login/login.tsx
> +                業務管理システム
業務管理システムのタイトルの位置が左揃えになっています。

2024-07-09 02:01 UTC, hirokitanya commented on app/auth/login/login.tsx
> +                業務管理システム
業務管理システムのテキストの揃え位置を中央に修正しました

2024-07-09 02:21 UTC, hirokitanya commented on app/auth/login/login.tsx
> +                業務管理システム
修正版の画像です。
![スクリーンショット 2024-07-09 111843](https://github.com/hirokitanya/next-storybook-for-beginners/assets/174312365/e023e23c-437f-4778-8bfa-ed3fb54f3ffe)

2024-07-09 02:44 UTC, fox-Taisei-Nakamura approved these changes

2024-07-09 02:49 UTC, merged