figmaの画面を作成
hirokitanya/next-storybook-for-beginners pull request #8
Opened 2024-07-09 09:58 UTC by hirokitanya

1.app/employee/employee.tsx を作成
2.interface EmployeeData をpropsとして受け取るようにする
3.app/employee/employee.stories.tsxを作成する。
4.figmaを参考にコンポーネントを作成

![スクリーンショット 2024-07-09 185316](https://github.com/fox-hound-ltd/next-storybook-for-beginners/assets/174312365/903bc5c8-12fb-4281-b50d-291ec496248e)
![スクリーンショット 2024-07-09 185240](https://github.com/fox-hound-ltd/next-storybook-for-beginners/assets/174312365/496c9d86-da9b-40c9-a153-363947ae9fc9)

2024-07-09 11:03 UTC, fox-Taisei-Nakamura requested changes
employeeディレクトリがissueのタスク内容と異なっています
修正してください

2024-07-09 11:09 UTC, fox-Taisei-Nakamura requested changes

2024-07-09 11:09 UTC, fox-Taisei-Nakamura commented on app/auth/employee/employee.tsx
> +                          {/* width: Fixed (50px)px;
不要なら削除してください

2024-07-09 11:09 UTC, fox-Taisei-Nakamura commented on app/auth/employee/dashboard.tsx
> +export default function Dashboard({ employee }: Readonly<{ employee: EmployeeData }>) {
なぜpageからemployeeを呼ばずにdashboard経由で呼んでいるのでしょうか？

2024-07-10 02:10 UTC, hirokitanya commented on app/auth/employee/employee.tsx
> +                          {/* width: Fixed (50px)px;
不要なコメントアウト箇所を削除しました。

2024-07-10 02:11 UTC, hirokitanya commented on app/auth/employee/dashboard.tsx
> +export default function Dashboard({ employee }: Readonly<{ employee: EmployeeData }>) {
dashboardページを作成した際と同じ構造でやるものだと思い込んでいたため、dashboard経由で呼んでいました。
dashboardファイルを削除し、employeeから呼び出す形に修正しました。

2024-07-10 02:35 UTC, fox-Taisei-Nakamura requested changes

2024-07-10 02:35 UTC, fox-Taisei-Nakamura commented on app/employee/employee.tsx
> +        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
`sx=`ではなく、tailwindのスタイルの指定にしてください

2024-07-10 02:35 UTC, fox-Taisei-Nakamura commented on app/employee/employee.tsx
> +                    <TableRow key={row.name} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
`sx=`ではなく、tailwindのスタイルの指定にしてください

2024-07-10 03:22 UTC, hirokitanya commented on app/employee/employee.tsx
> +        <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
該当箇所をtailwindでのスタイル指定に変更しました。

2024-07-10 03:22 UTC, hirokitanya commented on app/employee/employee.tsx
> +                    <TableRow key={row.name} sx={{ '&:last-child td, &:last-child th': { border: 0 } }}>
この個所は変更していません。

2024-07-10 03:47 UTC, fox-Taisei-Nakamura approved these changes

2024-07-10 03:49 UTC, merged